/*
 * Copyright, Aspect Security, Inc.
 *
 * This file is part of JavaSnoop.
 *
 * JavaSnoop is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JavaSnoop is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JavaSnoop.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.aspect.snoop.ui;

import com.aspect.snoop.util.IOUtil;
import com.aspect.snoop.util.UIUtil;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import org.jdesktop.application.Action;

public class EditJavaPolicyView extends javax.swing.JDialog {

    /** Creates new form EditJavaPolicyView */
    private File policyFile;

    public EditJavaPolicyView(java.awt.Frame parent, boolean modal, File policyFile) throws IOException {
        super(parent, modal);
        initComponents();
        this.policyFile = policyFile;

        String existingPolicy = new String ( IOUtil.getBytesFromFile(policyFile) );
        txtPolicy.setText(existingPolicy);
        txtPolicy.setCaretPosition(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPolicy = new javax.swing.JTextArea();
        btnSaveChanges = new javax.swing.JButton();
        btnMakeUnsafe = new javax.swing.JButton();
        btnMakeSafe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.aspect.snoop.JavaSnoop.class).getContext().getResourceMap(EditJavaPolicyView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtPolicy.setColumns(20);
        txtPolicy.setRows(5);
        txtPolicy.setName("txtPolicy"); // NOI18N
        jScrollPane1.setViewportView(txtPolicy);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.aspect.snoop.JavaSnoop.class).getContext().getActionMap(EditJavaPolicyView.class, this);
        btnSaveChanges.setAction(actionMap.get("saveChanges")); // NOI18N
        btnSaveChanges.setText(resourceMap.getString("btnSaveChanges.text")); // NOI18N
        btnSaveChanges.setName("btnSaveChanges"); // NOI18N

        btnMakeUnsafe.setText(resourceMap.getString("btnMakeUnsafe.text")); // NOI18N
        btnMakeUnsafe.setName("btnMakeUnsafe"); // NOI18N
        btnMakeUnsafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeUnsafeActionPerformed(evt);
            }
        });

        btnMakeSafe.setText(resourceMap.getString("btnMakeSafe.text")); // NOI18N
        btnMakeSafe.setName("btnMakeSafe"); // NOI18N
        btnMakeSafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeSafeActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        btnCancel.setAction(actionMap.get("cancelChanges")); // NOI18N
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMakeUnsafe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMakeSafe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveChanges)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveChanges)
                    .addComponent(btnMakeUnsafe)
                    .addComponent(btnMakeSafe)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMakeSafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeSafeActionPerformed

        // get /META-INF/safe.policy
        try {

            String name = "/META-INF/safe.policy";
            InputStream is = this.getClass().getResourceAsStream(name);
            byte[] bytes = IOUtil.getBytesFromStream(is);

            txtPolicy.setText( new String(bytes) );
            
        } catch(IOException ioe) {
            UIUtil.showErrorMessage(this,"Couldn't load safe policy: " + ioe.getMessage());
        }

    }//GEN-LAST:event_btnMakeSafeActionPerformed

    private void btnMakeUnsafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeUnsafeActionPerformed

        // get /META-INF/unsafe.policy
        try {

            String name = "/META-INF/unsafe.policy";
            InputStream is = this.getClass().getResourceAsStream(name);
            byte[] bytes = IOUtil.getBytesFromStream(is);

            txtPolicy.setText( new String(bytes) );

        } catch(IOException ioe) {
            UIUtil.showErrorMessage(this,"Couldn't load unsafe policy: " + ioe.getMessage());
        }

    }//GEN-LAST:event_btnMakeUnsafeActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws Exception {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    EditJavaPolicyView dialog = new EditJavaPolicyView(new javax.swing.JFrame(), true, new File("foo.txt"));

                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch(Exception e) {}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnMakeSafe;
    private javax.swing.JButton btnMakeUnsafe;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPolicy;
    // End of variables declaration//GEN-END:variables

    public boolean userAcceptedChanges() {
        return acceptedChanges;
    }

    public String getPolicy() {
        return policy;
    }
    
    private boolean acceptedChanges = false;
    private String policy = null;

    @Action
    public void saveChanges() {
        acceptedChanges = true;
        policy = txtPolicy.getText();
        dispose();
    }

    @Action
    public void cancelChanges() {
        acceptedChanges = false;
        dispose();
    }

}
